import './sass/main.scss';
import './js/mobile-menu'
import './js/about_modal'
import './js/reviews-slider'
import './js/animation-advantages'
import './js/gallery-animation'
import './js/modal'
import './js/modal-locations'
import './js/copyrights'
